# .github/workflows/ci.yml
name: CI

on:
 push:
   branches: [ main, dev ]
 pull_request:
   branches: [ main ]

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}

jobs:
 test:
   runs-on: buildjet-2vcpu-ubuntu-2204
   strategy:
     matrix:
       tf_version: ["1.13.0", "1.13.1"]
       aws_provider_version: ["5.64.0", "5.65.0"]

   steps:
   - uses: actions/checkout@v4

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build image
     run: |
       docker build -f images/terraform/Dockerfile \
         --build-arg TF_VERSION=${{ matrix.tf_version }} \
         --build-arg AWS_PROVIDER_VERSION=${{ matrix.aws_provider_version }} \
         -t test-image \
         .

   - name: Run tests
     run: |
       # Version check
       docker run --rm test-image version

       # Provider test
       mkdir -p test-tf
       chmod 777 test-tf
       cat > test-tf/main.tf <<EOF
       terraform {
         required_providers {
           aws = {
             source  = "hashicorp/aws"
             version = "${{ matrix.aws_provider_version }}"
           }
         }
       }
       EOF

       docker run --rm -v $(pwd)/test-tf:/workspace -w /workspace test-image init
       docker run --rm -v $(pwd)/test-tf:/workspace -w /workspace test-image providers

       # Debug mode
       docker run --rm test-image debug -c "echo 'Debug works'"

 build-multiarch:
   runs-on: ubuntu-latest
   if: github.event_name == 'push'
   needs: [test]

   steps:
   - uses: actions/checkout@v4

   - name: Set up QEMU
     uses: docker/setup-qemu-action@v3

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to Container Registry
     uses: docker/login-action@v3
     with:
       registry: ${{ env.REGISTRY }}
       username: ${{ github.repository_owner }}
       password: ${{ secrets.GITHUB_TOKEN }}

   - name: Extract metadata
     id: meta
     uses: docker/metadata-action@v5
     with:
       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
       tags: |
         type=ref,event=branch
         type=ref,event=pr
         type=sha,prefix={{branch}}-

   - name: Build and push
     uses: docker/build-push-action@v5
     with:
       context: .
       file: images/terraform/Dockerfile
       platforms: linux/amd64,linux/arm64
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
       cache-from: type=gha
       cache-to: type=gha,mode=max
