# .github/workflows/release.yml
name: Release

on:
 push:
   tags:
     - 'v*'

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}

jobs:
 release:
   runs-on: ubuntu-latest
   permissions:
     contents: write
     packages: write

   steps:
   - uses: actions/checkout@v4

   - name: Set up QEMU
     uses: docker/setup-qemu-action@v3

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to Container Registry
     uses: docker/login-action@v3
     with:
       registry: ${{ env.REGISTRY }}
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

   - name: Extract version
     id: version
     run: |
       VERSION=${GITHUB_REF#refs/tags/v}
       echo "version=$VERSION" >> $GITHUB_OUTPUT
       echo "tf_version=$(echo $VERSION | cut -d'-' -f1)" >> $GITHUB_OUTPUT
       echo "aws_version=$(echo $VERSION | cut -d'-' -f3)" >> $GITHUB_OUTPUT

   - name: Extract metadata
     id: meta
     uses: docker/metadata-action@v5
     with:
       images: |
         ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         ${{ github.repository }}
       tags: |
         type=semver,pattern={{version}}
         type=semver,pattern={{major}}.{{minor}}
         type=semver,pattern={{major}}
         type=raw,value=latest

   - name: Build and push multi-arch
     uses: docker/build-push-action@v5
     with:
       context: .
       file: images/terraform/Dockerfile
       platforms: linux/amd64,linux/arm64
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
       build-args: |
         TF_VERSION=${{ steps.version.outputs.tf_version }}
         AWS_PROVIDER_VERSION=${{ steps.version.outputs.aws_version }}
       cache-from: type=gha
       cache-to: type=gha,mode=max

   - name: Generate changelog
     id: changelog
     run: |
       if [ -f CHANGELOG.md ]; then
         # Extract current version section
         sed -n "/## \[${{ steps.version.outputs.version }}\]/,/## \[/p" CHANGELOG.md | head -n -1 > current_changelog.txt
         echo "changelog<<EOF" >> $GITHUB_OUTPUT
         cat current_changelog.txt >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT
       else
         echo "changelog=Release ${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
       fi

   - name: Create GitHub Release
     uses: actions/create-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ steps.version.outputs.version }}
       body: |
         ## Docker Images

         ```bash
         # GitHub Container Registry
         docker pull ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}

         # Docker Hub
         docker pull ${{ github.repository }}:${{ steps.version.outputs.version }}
         ```

         ## Changes
         ${{ steps.changelog.outputs.changelog }}
       draft: false
       prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
